apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-frontend
  description: This is an example frontend component for Backstage.
  tags:
    - frontend
    - example
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/backstage/backstage
spec:
  type: website
  lifecycle: production
  owner: team-a
  system: example-system
  consumesApis:
    - example-api

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-data-pipeline
  description: This is an example data pipeline component for Backstage.
  tags:
    - example
spec:
  type: data
  lifecycle: production
  owner: datanaut
  system: redshift-etl
  providesApis:
    - 368167702271.us-east-2.data-experience-test.dev.public.model_b
    - 368167702271.us-east-2.data-experience-test.dev.public.model_a
